---
# Source: masterdata/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: masterdata
    helm.sh/chart: masterdata-12.0.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mosip
  name: release-name-masterdata
  annotations:
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: masterdata
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
        
        prometheus.io/scrape: "true"
       
      labels:
        app.kubernetes.io/name: masterdata
        helm.sh/chart: masterdata-12.0.2
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: release-name-masterdata
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: masterdata
                    app.kubernetes.io/instance: release-name
                namespaces:
                  - "default"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      initContainers:
      containers:
        - name: masterdata
          image: docker.io/mosipqa/kernel-masterdata-service:develop
          imagePullPolicy: Always
          env:
            - name: container_user
              value: mosip
            - name: JDK_JAVA_OPTIONS
              value: -Xms1500M -Xmx1500M
          envFrom:
            - configMapRef:
                name: global
            - configMapRef:
                name: config-server-share
            - configMapRef:
                name: artifactory-share
          ports:
            - name: spring-service
              containerPort: 8086
          resources:
            limits:
              cpu: 500m
              memory: 2250Mi
            requests:
              cpu: 100m
              memory: 1500Mi
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /v1/masterdata/actuator/health
              port: 8086
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /v1/masterdata/actuator/health
              port: 8086
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /v1/masterdata/actuator/health
              port: 8086
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
