---
# Source: digitalcard/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: digitalcard
    helm.sh/chart: digitalcard-12.0.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mosip
  name: release-name-digitalcard
  annotations:
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: digitalcard
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
        
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: digitalcard
        helm.sh/chart: digitalcard-12.0.2
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: release-name-digitalcard
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: digitalcard
                    app.kubernetes.io/instance: release-name
                namespaces:
                  - "default"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      initContainers:
      containers:
        - name: digitalcard
          image: docker.io/mosipdev/digital-card-service:develop
          imagePullPolicy: Always
          env:
            - name: container_user
              value: mosip
            - name: JDK_JAVA_OPTIONS
              value: -Xms2250M -Xmx2250M
          envFrom:
              - configMapRef:
                  name: global
              - configMapRef:
                  name: config-server-share
              - configMapRef:
                  name: artifactory-share
          ports:
            - name: spring-service
              containerPort: 9092
          resources:
            limits:
              cpu: 300m
              memory: 3000Mi
            requests:
              cpu: 100m
              memory: 1000Mi
          startupProbe:
            failureThreshold: 10
            httpGet:
              path: /v1/digitalcard/actuator/health
              port: 9092
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /v1/digitalcard/actuator/health
              port: 9092
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /v1/digitalcard/actuator/health
              port: 9092
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
