kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "status-check.serviceAccountName" . }}
  labels:
    {{- include "status-check.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "status-check.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "status-check.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
