kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Values.job.rolebindingname }}-{{ .Release.Namespace }}"
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3" # The RoleBinding will execute after the Role
subjects:
  - kind: ServiceAccount
    name: {{ template "regclient.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: "{{ .Values.job.rolename }}-{{ .Release.Namespace }}"
  apiGroup: rbac.authorization.k8s.io
