kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: "{{ .Values.job.rolename }}-{{ .Release.Namespace }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4" #The Role will execute after the ServiceAccount
rules:
  - apiGroups: [""]
    resources: ["pods","configmaps", "secrets"]
    verbs: ["create", "delete", "patch"]
