# See https://github.com/helm/chart-testing#configuration
helm-extra-args: --timeout 600s
check-version-increment: true
debug: true
lint-conf: .github/lintconf.yaml
chart-yaml-schema: .github/chart-schema.yaml
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - confluentinc=https://confluentinc.github.io/cp-helm-charts/