---
# Source: partner-onboarder/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: partner-onboarder
    helm.sh/chart: partner-onboarder-12.0.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mosip
  name: release-name-partner-onboarder
  annotations:
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: partner-onboarder
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
        
        prometheus.io/scrape: "true"
       
      labels:
        app.kubernetes.io/name: partner-onboarder
        helm.sh/chart: partner-onboarder-12.0.2
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: release-name-partner-onboarder
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: partner-onboarder
                    app.kubernetes.io/instance: release-name
                namespaces:
                  - "default"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      initContainers:
      containers:
        - name: partner-onboarder
          image: docker.io/mosipqa/partner-onboarder:develop
          imagePullPolicy: Always
          env:
            - name: container_user
              value: mosip
          envFrom:
             - configMapRef:
                 name: env-config
             - secretRef:
                 name: release-name-partner-onboarder
          ports:
            - name: spring-service
              containerPort: 8080
          resources:
            limits: {}
            requests:
              cpu: 100m
              memory: 1000Mi
          startupProbe:
            exec:
              command:
              - ls
              - /home/mosip/reports/abis.html
            failureThreshold: 60
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
              - ls
              - /home/mosip/reports/abis.html
            failureThreshold: 6
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - ls
              - /home/mosip/reports/abis.html
            failureThreshold: 6
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
