---
# Source: websub-consolidator/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: websub-consolidator
    helm.sh/chart: websub-consolidator-12.0.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mosip
  name: release-name-websub-consolidator
  namespace: default
---
# Source: websub-consolidator/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-name-websub-consolidator
  namespace: "default"
  labels:
    app.kubernetes.io/name: websub-consolidator
    helm.sh/chart: websub-consolidator-12.0.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mosip
rules:
  - apiGroups:
      - "*"
    resources:
      - endpoints
      - pods
      - nodes
      - services
    verbs:
      - get
      - list
---
# Source: websub-consolidator/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: websub-consolidator
    helm.sh/chart: websub-consolidator-12.0.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mosip
  name: release-name-websub-consolidator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-name-websub-consolidator
subjects:
  - kind: ServiceAccount
    name: release-name-websub-consolidator
    namespace: default
---
# Source: websub-consolidator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: websub-consolidator
    helm.sh/chart: websub-consolidator-12.0.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mosip
  name: release-name-websub-consolidator
  annotations:
spec:
  type: ClusterIP
  
  ports:
    - port: 80
      protocol: TCP 
      targetPort: 9192
  selector:
    app.kubernetes.io/name: websub-consolidator
    app.kubernetes.io/instance: release-name
---
# Source: websub-consolidator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: websub-consolidator
    helm.sh/chart: websub-consolidator-12.0.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mosip
  name: release-name-websub-consolidator
  annotations:
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: websub-consolidator
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
       
      labels:
        app.kubernetes.io/name: websub-consolidator
        helm.sh/chart: websub-consolidator-12.0.2
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: release-name-websub-consolidator
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: websub-consolidator
                    app.kubernetes.io/instance: release-name
                namespaces:
                  - "default"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      initContainers:
      containers:
        - name: websub-consolidator
          image: docker.io/mosipqa/consolidator-websub-service:develop
          imagePullPolicy: Always
          env:
            - name: container_user
              value: mosip
            - name: JDK_JAVA_OPTIONS
              value: -Xms750M -Xmx750M
          envFrom:
            - configMapRef:
                name: global
            - configMapRef:
                name: config-server-share
          resources:
            limits:
              cpu: 200m
              memory: 1500Mi
            requests:
              cpu: 200m
              memory: 500Mi
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /consolidator/actuator/health
              port: 9192
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /consolidator/actuator/health
              port: 9192
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /consolidator/actuator/health
              port: 9192
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
