---
# Source: apitestrig/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: apitestrig
    helm.sh/chart: apitestrig-12.0.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mosip
  name: authdemo
  annotations:
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: apitestrig
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: apitestrig
        helm.sh/chart: apitestrig-12.0.2
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: release-name-apitestrig-foo
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: apitestrig
                    app.kubernetes.io/instance: release-name
                namespaces:
                  - "default"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      initContainers:
      containers:
        - name: apitestrig
          image: docker.io/mosipqa/authentication-demo-service:develop
          imagePullPolicy: Always
          env:
            - name: container_user
              value: mosip
            - name: JDK_JAVA_OPTIONS
              value: -Xms1500M -Xmx1500M
          envFrom:
            - configMapRef:
                name: global
            - configMapRef:
                name: s3
            - configMapRef:
                name: keycloak-host
            - configMapRef:
                name: db-cm
            - configMapRef:
                name: apitestrig
            - configMapRef:
                name: config-server-share
            - configMapRef:
                name: artifactory-share
            - secretRef:
                name: s3
            - secretRef:
                name: keycloak-client-secrets
            - secretRef:
                name: db-secrets
          ports:
            - name: spring-service
              containerPort: 8082
          resources:
            limits:
              cpu: 300m
              memory: 2000Mi
            requests:
              cpu: 300m
              memory: 2000Mi
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /v1/identity/actuator/health
              port: 8082
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /v1/identity/actuator/health
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /v1/identity/actuator/health
              port: 8082
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
