---
# Source: prereg-datasync/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: prereg-datasync
    helm.sh/chart: prereg-datasync-12.0.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mosip
  name: release-name-prereg-datasync
  annotations:
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: prereg-datasync
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
        
        prometheus.io/scrape: "true"
       
      labels:
        app.kubernetes.io/name: prereg-datasync
        helm.sh/chart: prereg-datasync-12.0.2
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: release-name-prereg-datasync
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: prereg-datasync
                    app.kubernetes.io/instance: release-name
                namespaces:
                  - "default"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      initContainers:
      containers:
        - name: prereg-datasync
          image: docker.io/mosipqa/pre-registration-datasync-service:develop
          imagePullPolicy: Always
          env:
            - name: container_user
              value: mosip
            - name: JDK_JAVA_OPTIONS
              value: -Xms2000M -Xmx2000M
          envFrom:
            - configMapRef:
                name: global
            - configMapRef:
                name: config-server-share
            - configMapRef:
                name: artifactory-share
          ports:
            - name: spring-service
              containerPort: 9094
          resources:
            limits:
              cpu: 500m
              memory: 2500Mi
            requests:
              cpu: 200m
              memory: 1000Mi
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /preregistration/v1/actuator/health
              port: 9094
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /preregistration/v1/actuator/health
              port: 9094
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /preregistration/v1/actuator/health
              port: 9094
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
