apiVersion: v2
name: minio-client
description: A Helm chart to deploy minio-client as an utility to remove apitestrig reports from minio
type: application
version: 12.0.2
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - minioclient
maintainers:
  - email: info@mosip.io
    name: MOSIP
