apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}

data:
  config.json: |-
   {"baseUrl":"https://{{ .Values.resident.apiHost }}/resident/v1",
    "version": "v1",
    "validateToken": "admin/authorize/admin/validateToken",
    "login": "/login/",
    "logout": "/logout/user"}
  default.conf: |-
    server {
      listen       8080;
      server_name  localhost;
      add_header X-Frame-Options DENY;

      #charset koi8-r;
      #access_log  /var/log/nginx/host.access.log  main;
      #index  index.html index.htm;

      location / {
          root   /usr/share/nginx/html;
      }
    }


