{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  hosts:
  - "*"
  gateways:
    {{- if .Values.istio.existingGateway }}
    - {{ .Values.istio.existingGateway }}
    {{- else }}
    - {{ template "common.names.fullname" . }}
    {{- end }}
  http:
  - match:
    - uri:
        exact: /opencrvs-mediator/birth
    rewrite:
      uri: /birth
    route:
    - destination:
        host: {{ template "common.names.fullname" . }}
        port:
          number: {{ .Values.service.port }}
    headers:
      request:
        set:
          x-forwarded-proto: https
  - match:
    - uri:
        exact: /opencrvs-mediator/death
    rewrite:
      uri: /death
    route:
    - destination:
        host: {{ template "common.names.fullname" . }}
        port:
          number: {{ .Values.service.port }}
    headers:
      request:
        set:
          x-forwarded-proto: https
{{- end }}
