# Default values for cronjob-rigs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cronjob:
  name: restart-cronjob

namespaces:
  - name: packetcreator
    enabled: true
    deploymentName: packetcreator
  - name: authdemo
    enabled: true
    deploymentName: authdemo
  - name: kernel
    enabled: true
    deploymentName: idgenerator

schedule:
  crontime: "0 3 * * *"   ## run cronjob every day at 3 AM (time hr: 0-23 )

## "backoff" strategy - It is used when dealing with resources that are retrying or recovering from failures.
##
backoffLimit: 0

serviceAccount:
  create: true
  name: pod-deleter
  namespace: infra-admin

rbac:
  create: true
  name: pod-deleter-rolebinding
  namespace: infra-admin
  apiGroup: rbac.authorization.k8s.io

role:
  create: true
  name: "pod-deleter-role"
