---
# Source: otpmanager/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: otpmanager
    helm.sh/chart: otpmanager-12.0.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mosip
  name: release-name-otpmanager
  annotations:
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: otpmanager
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
        
        prometheus.io/scrape: "true"
       
      labels:
        app.kubernetes.io/name: otpmanager
        helm.sh/chart: otpmanager-12.0.2
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: release-name-otpmanager
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: otpmanager
                    app.kubernetes.io/instance: release-name
                namespaces:
                  - "default"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      initContainers:
      containers:
        - name: otpmanager
          image: docker.io/mosipqa/kernel-otpmanager-service:develop
          imagePullPolicy: Always
          env:
            - name: container_user
              value: mosip
            - name: JDK_JAVA_OPTIONS
              value: -Xms1000M -Xmx1000M
          envFrom:
            - configMapRef:
                name: global
            - configMapRef:
                name: config-server-share
            - configMapRef:
                name: artifactory-share
          ports:
            - name: spring-service
              containerPort: 8085
          resources:
            limits:
              cpu: 500m
              memory: 1750Mi
            requests:
              cpu: 100m
              memory: 1000Mi
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /v1/otpmanager/actuator/health
              port: 8085
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /v1/otpmanager/actuator/health
              port: 8085
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /v1/otpmanager/actuator/health
              port: 8085
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
