apiVersion: v2
name: landing-page
description: A Helm chart to installed Downloader for Regstration Client Application
type: application
version: 12.0.2
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - landing-page
  - registration
  - client
maintainers:
  - email: info@mosip.io
    name: MOSIP
