apiVersion: v2
name: resident-ui
description: A Helm chart for resident-ui
type: application
version: 0.0.1
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - resident-ui
  - kernel
maintainers:
  - email: info@mosip.io
    name: MOSIP
