apiVersion: v2
name: gc-util
description: A Helm chart to clear completed jobs from the kubernetes cluster
type: application
version: 0.0.8
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - deletecron
  - gcutil
maintainers:
  - email: info@mosip.io
    name: MOSIP
