# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: archive-db-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: postgres
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  SU_USER_PWD: {{ .Values.databases.archive_db.su_user_pwd | b64enc | quote }}
  DBUSER_PWD: {{ .Values.databases.archive_db.db_pwd | b64enc | quote }}
  ARCHIVE_DB_PASS: {{ .Values.databases.archive_db.archive_db_password | b64enc | quote }}
