base:
  db_prefix: "mosip"
  db_user: postgres
  db_hostname: "postgres-postgresql.postgres"
  db_port: "5432"
  # if this is not false it will directly take pass from this variable, else it will take from db_pass_secretref
  db_pass_direct: false
  db_pass_secretref:
    name: postgres-postgresql
    key: postgresql-password
  es_url: http://elasticsearch-master.cattle-logging-system:9200
  kibana_url: http://kibana.cattle-logging-system:5601

debezium_connectors:
  image: mosipid/debezium-init
  imageTag: 1.2.0.1
  imagePullPolicy: Always

  enabled: true
  existingConfigMap: null
  delay_between_connectors: "0s"
  dbs:
  - name: "mosip_master"
    tables: "master.doc_type,master.registration_center"
  - name: "mosip_audit"
    tables: "audit.app_audit_log"
  - name: "mosip_prereg"
    tables: "prereg.applicant_demographic,prereg.applicant_demographic_consumed,prereg.applicant_document,prereg.applicant_document_consumed,prereg.reg_appointment,prereg.reg_appointment_consumed,prereg.reg_available_slot,prereg.otp_transaction"
  - name: "mosip_ida"
    tables: "ida.auth_transaction"
  - name: "mosip_regprc"
    tables: "regprc.registration,regprc.registration_list"

es_kafka_connectors:
  image: mosipid/es-kafka-connect-init
  imageTag: 1.2.0.1
  imagePullPolicy: Always

  enabled: true
  existingConfigMap: null
  delay_between_connectors: "0s"

kibana_enabled: {}

## "backoff" strategy - It is used when dealing with resources that are retrying or recovering from failures.
##
backoffLimit: 0
