---
# Source: landing-page/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: landing-page
    helm.sh/chart: landing-page-12.0.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mosip
  name: release-name-landing-page
  annotations:
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: landing-page
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: landing-page
        helm.sh/chart: landing-page-12.0.2
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: release-name-landing-page-foo
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: landing-page
                    app.kubernetes.io/instance: release-name
                namespaces:
                  - "default"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      initContainers:
      containers:
        - name: landing-page
          image: docker.io/nginx:latest
          imagePullPolicy: Always
          env:
          envFrom:
            - configMapRef:
                name: global
          volumeMounts:
            - name: landing-page
              mountPath:  /usr/share/nginx/html/index.html
              subPath: index.html
          ports:
            - name: container-port
              containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 1500Mi
            requests:
              cpu: 100m
              memory: 1500Mi
          startupProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
      volumes:
        - name: landing-page
          configMap:
            name: release-name-landing-page-index
