{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  hosts:
  - "*"
  gateways:
    {{- if .Values.istio.gateways }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.istio.gateways "context" $ ) | nindent 6 }}
    {{- else }}
    - {{ template "common.names.fullname" . }}
    {{- end }}
  http:
  - name: .well-known
    match:
      {{- if .Values.istio.prefix }}
      {{- range $key, $value := .Values.istio.prefix }}
      - uri:
          prefix: {{ $value }}
      {{- end }}
      {{- end }}
    route:
    - destination:
        host: {{ template "common.names.fullname" . }}
        port:
          number: {{ .Values.service.port }}
    corsPolicy:
    {{- include "common.tplvalues.render" ( dict "value" .Values.istio.corsPolicy "context" $ ) | nindent 6 }}
    headers:
      request:
        set:
          x-forwarded-proto: https
{{- end }}
