apiVersion: v2
name: db-password-gen
description: A Helm chart for Kubernetes to generate passwords for postgres DBs.
type: application
version: 12.0.2
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x

home: https://mosip.io
keywords:
  - postgres
  - db-password-gen
  - database
maintainers:
  - email: info@mosip.io
    name: MOSIP 
