apiVersion: v2
name: s3-utility
description: A Helm chart to deploy s3 utility to remove apitestrig reports from minio
type: application
version: 1.0.1
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - minioclient
maintainers:
  - email: info@mosip.io
    name: MOSIP
