{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ template "common.names.fullname" . }}
    namespace: {{ .Release.Namespace }}
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.rewrite_prefix_uri }}
spec:
    rules:
    - http:
        paths:
        - path: {{ .Values.ingress.prefix }}
          pathType: Prefix
          backend:
            service:
              name: {{ template "common.names.fullname" . }}
              port:
                number: {{ .Values.service.port }}
{{- end }}
