---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "packetcreator.serviceAccountName" . }}-pods-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "packetcreator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "packetcreator.serviceAccountName" . }}-pods-role
  apiGroup: rbac.authorization.k8s.io
