kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-delete-binding
  namespace: dslrig
subjects:
- kind: ServiceAccount
  name: my-service-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: pod-delete-role
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-delete-binding
  namespace: apitestrig
subjects:
  - kind: ServiceAccount
    name: my-service-account
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: pod-delete-role
  apiGroup: rbac.authorization.k8s.io
