kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dslrig
  name: pod-delete-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: apitestrig
  name: pod-delete-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]



