# Default values for cronjob-rigs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cronjob:
  name: restart-cronjob

namespaces:
  - name: packetcreator
    enabled: true
    deploymentName: packetcreator
  - name: authdemo
    enabled: true
    deploymentName: authdemo

schedule:
  crontime: "0 3 * * *"   ## run cronjob every day at 3 AM (time hr: 0-23 )

serviceAccount:
  create: true
  name: pod-deleter
  namespace: dslrig

rbac:
  create: true
  name: pod-deleter-rolebinding
  namespace: dslrig
  apiGroup: rbac.authorization.k8s.io

role:
  create: true
  name: "pod-deleter-role"
