---
# Source: resident-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: resident-app
    helm.sh/chart: resident-app-12.0.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mosip
  name: release-name-resident-app
  annotations:
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: resident-app
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: resident-app
        helm.sh/chart: resident-app-12.0.2
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: resident-app
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: resident-app
                    app.kubernetes.io/instance: release-name
                namespaces:
                  - "default"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      initContainers:
      containers:
        - name: resident-app
          image: docker.io/mosipqa/mimoto:develop
          imagePullPolicy: Always
          env:
            - name: container_user
              value: mosip
            - name: JDK_JAVA_OPTIONS
              value: -Xms2250M -Xmx2250M
          envFrom:
            - configMapRef:
                name: global
            - configMapRef:
                name: config-server-share
            - configMapRef:
                name: artifactory-share
          volumeMounts:
            - name: landing-folder
              mountPath: /mnt/landing
          ports: []
          resources:
            limits:
              cpu: 500m
              memory: 3000Mi
            requests:
              cpu: 100m
              memory: 1000Mi
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /v1/mimoto/actuator/health
              port: 8088
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /v1/mimoto/actuator/health
              port: 8088
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /v1/mimoto/actuator/health
              port: 8088
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
      volumes:
        - name: landing-folder
          emptyDir: {}
