{{- if .Values.istio.enabled  }}
{{- if .Values.istio.gateways }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ template "common.names.fullname" . }}-gateway
spec:
  selector:
    {{- include "common.tplvalues.render" (dict "value" .Values.istio.ingressController "context" $) | nindent 4 }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      {{- include "common.tplvalues.render" ( dict "value" .Values.istio.hosts "context" $) | nindent 6  }}
{{- end }}
{{- end }}
