kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: exec-pod-role
rules:
  - apiGroups: [""]
    resources: ["pods","pods/exec"]
    verbs: ["get", "list", "delete", "exec", "create"]
