{{- range $volume_name, $volume := .Values.volumes }}
{{- if and $volume.enabled (not $volume.existingClaim) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $volume_name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if $.Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if $.Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    "helm.sh/resource-policy": keep 
spec:
  accessModes:
  {{- if not (empty $volume.accessModes) }}
  {{- range $volume.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- else }}
    - {{ $volume.accessMode | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ $volume.size | quote }}
  {{- include "common.storage.class" (dict "persistence" $volume "global" $.Values.global) | nindent 2 }}
  {{- if $volume.dataSource }}
  dataSource: {{- include "common.tplvalues.render" (dict "value" $volume.dataSource "context" $) | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
