---
# Source: reporting/templates/debezium.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-deploy
  labels:
    app: debezium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium
  template:
    metadata:
      labels:
        app: debezium
    spec:
      containers:
      - name: debezium-container
        image: debezium/connect:1.7.0.Final
        imagePullPolicy: Always
        env:
          - name: BOOTSTRAP_SERVERS
            value: kafka:9092
          - name: GROUP_ID
            value: "1"
          - name: OFFSET_STORAGE_TOPIC
            value: debez-connect-offsets
          - name: CONFIG_STORAGE_TOPIC
            value: debez-connect-configs
          - name: STATUS_STORAGE_TOPIC
            value: debez-connect-status
        ports:
        - containerPort: 8083
      - name: debezium-fixer
        image: mosipqa/debezium-fixer:develop
        imagePullPolicy: Always
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: STARTUP_DELAY
          value: 30s
        - name: PROBE_TIME_PERIOD
          value: 30s
        - name: ERROR_LEVEL1
          value: "failed"
        - name: ERROR_LEVEL2
          value: "PSQLException: An I/O error occurred while sending to the backend"
