apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-upgrade-job
  labels:
    {{- include "postgres-upgrade.labels" . | nindent 4 }}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        {{- include "postgres-upgrade.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: postgres-upgrade-job
        sidecar.istio.io/inject: "false"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "postgres-upgrade.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.jobSecurityContext | nindent 8 }}
      restartPolicy: Never  # This is one time job
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SU_USER_PWD
            value: {{ .Values.database.su.su_password }}
          - name: DB_USER_PWD
            value: {{ .Values.database.dbu.dbu_password }}
          envFrom:
            - configMapRef:
                name: postgres-upgrade-env-config
          volumeMounts:
            - name: upgrade-csv
              mountPath: /home/mosip/repos/db_upgrade_scripts/upgrade.csv
              subPath: upgrade.csv
      volumes:
        - name: upgrade-csv
          configMap:
            name: {{ template "common.names.fullname" . }}
            items:
              - key: upgrade.csv
                path: upgrade.csv
