---
# Source: mosip-file-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mosip-file-server
    helm.sh/chart: mosip-file-server-12.0.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mosip
  name: release-name-mosip-file-server
  annotations:
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: mosip-file-server
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: mosip-file-server
        helm.sh/chart: mosip-file-server-12.0.2
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: release-name-mosip-file-server-foo
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: mosip-file-server
                    app.kubernetes.io/instance: release-name
                namespaces:
                  - "default"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      initContainers:
      containers:
        - name: mosipfileserver
          image: docker.io/mosipqa/mosip-file-server:develop
          imagePullPolicy: Always
          command:
            - /bin/bash
          args:
            - -c
            - mkdir -p /home/mosip/mosip-file-server/.well-known/mosipvc/ /home/mosip/mosip-file-server/files/mobileapp/
              && cp /mnt/mosip-file-server/.well-known/mosipvc/*  /home/mosip/mosip-file-server/.well-known/mosipvc/
              && /bin/bash  /home/mosip/get-cert.sh && echo 'starting nginx'&& nginx && sleep
              infinity;
          env:
            - name: healthcheck_url_env
              value: http://localhost:8080/.well-known/
            - name: host
              value: 
          envFrom:
            - configMapRef:
                name: config-server-share
            - configMapRef:
                name: mosip-file-server
            - secretRef:
                name: keycloak-client-secret
          volumeMounts:
            - name: wellknown
              mountPath:  /mnt/mosip-file-server/.well-known/mosipvc/

            - name: mobileapp
              mountPath:  /home/mosip/mosip-file-server/files/mobileapp//index.html
              subPath: index.html

          ports:
            - name: container-port
              containerPort: 8080
          resources:
            limits: {}
            requests:
              cpu: 100m
              memory: 1500Mi
          startupProbe:
            failureThreshold: 10
            httpGet:
              path: /.well-known/
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /.well-known/
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /.well-known/
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
      volumes:
        - name: wellknown
          configMap:
            name: wellknown-cm
        - name: mobileapp
          configMap:
            name: mobileapp-cm
            items:
              - key: index.html
                path: index.html
