apiVersion: v2
name: postgres-init
description: A Helm chart for Kubernetes to initialize various Postgres DBs.
type: application
version: 12.0.2
appVersion: 1.2.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x

home: https://mosip.io
keywords:
  - postgres
  - db
  - database
maintainers:
  - email: info@mosip.io
    name: MOSIP
