apiVersion: v2
name: mosip-compliance-toolkit
description: A Helm chart for mosip-compliance-toolkit Application service
type: application
version: 12.0.2
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - mosip-compliance-toolkit
  - kernel
maintainers:
  - email: info@mosip.io
    name: MOSIP 
