---
# Source: regclient/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: regclient
    helm.sh/chart: regclient-12.0.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mosip
  name: release-name-regclient
  annotations:
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: regclient
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: regclient
        helm.sh/chart: regclient-12.0.2
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: release-name-regclient-foo
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: regclient
                    app.kubernetes.io/instance: release-name
                namespaces:
                  - "default"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      initContainers:
      containers:
        - name: regclient
          image: docker.io/mosipqa/registration-client:develop
          imagePullPolicy: Always
          env:
            - name: client_version_env
              value: 1.2.1-SNAPSHOT 
            - name: crypto_key_env
              value: bBQX230Wskq6XpoZ1c+Ep1D+znxfT89NxLQ7P4KFkc4=
            - name: client_upgrade_server_env
              value: https://regclient.sandbox.xzy.net
            - name: healthcheck_url_env
              value: http://api-internal.sandbox.mosip.net/v1/syncdata/actuator/health 
            - name: host_name_env
              value: https://api-internal.sandbox.mosip.net
            - name: client_certificate_env
              value: mosip_cer.cer
            - name: signer_timestamp_url_env
              value: http://timestamp.comodoca.com/rfc3161
          envFrom:
            - configMapRef:
                name: artifactory-share
            - secretRef:
                name: keystore-secret-env
          volumeMounts:
            - name: maven-xml-and-regclient-certs
              mountPath:  /home/mosip/build_files/
            - name: landing-page
              mountPath:  /var/www/html/index.html
              subPath: index.html
          ports:
            - name: container-port
              containerPort: 80
          resources:
            limits:
              cpu: 200m
              memory: 2000Mi
            requests:
              cpu: 100m
              memory: 1500Mi
          startupProbe:
            failureThreshold: 10
            httpGet:
              path: /registration-client/1.2.1-SNAPSHOT/reg-client.zip
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /registration-client/1.2.1-SNAPSHOT/reg-client.zip
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /registration-client/1.2.1-SNAPSHOT/reg-client.zip
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
      volumes:
        - name: maven-xml-and-regclient-certs
          projected:
            sources:
              - configMap:
                  name: regclient-certs
              - configMap:
                  name: release-name-regclient
                  items:
                    - key: maven-metadata.xml
                      path: maven-metadata.xml
                    - key: logback.xml
                      path: logback.xml
    
        - name: landing-page
          configMap:
            name: release-name-regclient-index
