---
# Source: websub/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: websub
    helm.sh/chart: websub-12.0.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mosip
  name: release-name-websub
  annotations:
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: websub
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
       
      labels:
        app.kubernetes.io/name: websub
        helm.sh/chart: websub-12.0.2
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: release-name-websub
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: websub
                    app.kubernetes.io/instance: release-name
                namespaces:
                  - "default"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      initContainers:
      containers:
        - name: websub
          image: docker.io/mosipqa/websub-service:develop
          imagePullPolicy: Always
          env:
            - name: container_user
              value: mosip
            - name: JDK_JAVA_OPTIONS
              value: -Xms2000M -Xmx2000M
          envFrom:
            - configMapRef:
                name: global
            - configMapRef:
                name: config-server-share
          ports:
            - name: spring-service
              containerPort: 9191
          resources:
            limits:
              cpu: 2000m
              memory: 8000Mi
            requests:
              cpu: 200m
              memory: 1000Mi
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /hub/actuator/health
              port: 9191
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /hub/actuator/health
              port: 9191
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /hub/actuator/health
              port: 9191
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
