---
# Source: biosdk-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: biosdk-service
    helm.sh/chart: biosdk-service-12.0.2
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: mosip
  name: release-name-biosdk-service
  annotations:
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: biosdk-service
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
       
      labels:
        app.kubernetes.io/name: biosdk-service
        helm.sh/chart: biosdk-service-12.0.2
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: release-name-biosdk-service
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: biosdk-service
                    app.kubernetes.io/instance: release-name
                namespaces:
                  - "default"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      initContainers:
      containers:
        - name: biosdk-service
          image: docker.io/mosipqa/biosdk-server:develop
          imagePullPolicy: Always
          env:
            - name: container_user
              value: mosip
            - name: JDK_JAVA_OPTIONS
              value: -Xms1250M -Xmx1250M
            - name: biosdk_zip_file_path
              value: http://artifactory.artifactory/artifactory/libs-release-local/biosdk/biosdk-lib.zip
            - name: biosdk_bioapi_impl
              value: io.mosip.mock.sdk.impl.SampleSDK
          envFrom:
          ports:
            - name: spring-service
              containerPort: 9099
          resources:
            limits:
              cpu: 300m
              memory: 2000Mi
            requests:
              cpu: 100m
              memory: 500Mi
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /biosdk-service/actuator/health
              port: 9099
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /biosdk-service/actuator/health
              port: 9099
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /biosdk-service/actuator/health
              port: 9099
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
